version: "2"
services:
  web:
    image: joumichy/mypugrelease:latest
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:80"
